model:
  type: linear_regression
  feature_columns:
    - Levy
    - Manufacturer
    - Model
    - Prod. year
    - Category
    - Leather interior
    - Fuel type
    - Engine volume
    - Mileage
    - Cylinders
    - Gear box type
    - Drive wheels
    - Doors
    - Wheel
    - Color
    - Airbags
  target_column: Price

split:
  test_size: 0.2
  random_state: 42
